name: CI
on:
  pull_request:
    branches: [main, develop]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pdm install -G dev
      - name: Verify pytest
        run: |
          pdm run pytest --version
      - name: Run pre-commit
        run: |
          pdm run pre-commit run --all-files
      - name: Run tests
        run: |
          pdm pytest --cov --junitxml=junit.xml -o junit_family=legacy
      - name: Run linter
        run: |
          pdm run ruff check .
      - name: Upload coverage to Codecov
        if: ${{ !cancelled() && matrix.python-version == '3.12' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
